### ISSUE TITLE
bug: 기존 답변 기록이 사라지는 버그

### ISSUE THREAD

**Issue by psymoney** [RightMemeRightNow/right-meme-right-now#38]
## 📌Bug Description
보관하는 상태가 사라진 건지 UI에 반영이 안되는건지는 확인하지 못하였음.

버그 재현 방법:
1. 특정 질문의 답변을 선택 후 다음으로 넘어간다
2. 다음 질문에서 답변을 선택하지 않은 채로 이전으로 돌아간다
3. 지금까지의 답변 내역이 사라진다

특정 질문 선택:
![image](https://github.com/RightMemeRightNow/right-meme-right-now/assets/78402001/63f14558-ede0-4cbe-9c53-2d60da30f08a)
다음질문에서 답안을 선택하지 않음:
![image](https://github.com/RightMemeRightNow/right-meme-right-now/assets/78402001/d4d2a144-6cab-41f5-b74a-3be70645ed54)
이전을 누르게 되면:
![image](https://github.com/RightMemeRightNow/right-meme-right-now/assets/78402001/b0c6a028-02d5-4c33-bece-db1b5da0d354)
답변 내역이 사라진다

**Comment by KJeeu** [comment]
UI에 반영이 되지 않았습니다.
수정해두겠습니다!
